Repository PUPT-FLSS-ORG/PUPT-FLSS, pull requests merged in 2024-12, with the labels that each got.

#80 Add Start Date on Preferences Submission
  backend/app/Console/Commands/CheckPreferencesDeadline.php
  backend/app/Http/Controllers/PreferenceController.php
  backend/app/Http/Controllers/ReportsController.php
  backend/app/Models/PreferencesSetting.php
  backend/database/migrations/2024_09_30_004059_create_preferences_settings_table.php
  backend/database/sql/template/pupt_flss_official_v1.sql
  frontend/src/app/core/components/admin/faculty-pref/faculty-pref.component.html
  frontend/src/app/core/components/admin/faculty-pref/faculty-pref.component.ts
  frontend/src/app/core/components/admin/overview/overview.component.ts
  frontend/src/app/core/services/admin/overview/overview.service.ts
  frontend/src/app/core/services/faculty/preference/preferences.service.ts
  frontend/src/app/shared/dialog-action/dialog-action.component.html
  frontend/src/app/shared/dialog-action/dialog-action.component.scss
  frontend/src/app/shared/dialog-action/dialog-action.component.ts
Labels: enhancement

#81 Email Active Admin for Change Request
  backend/app/Http/Controllers/EmailController.php
  backend/app/Jobs/NotifyAdminOfPreferenceChangeJob.php
  backend/resources/views/emails/change_request.blade.php
  backend/routes/api.php
  backend/routes/web.php
  frontend/package-lock.json
Labels: new feature

#84 Refactor preferences process to allow multi-day/time association to a course
  backend/app/Console/Commands/AddApiKey.php
  backend/app/Console/Commands/GenerateApiKey.php
  backend/app/Console/Commands/GetApiKeys.php
  backend/app/Http/Controllers/External/.gitkeep
  backend/app/Http/Controllers/External/v1/ExternalController.php
  backend/app/Http/Controllers/PreferenceController.php
  backend/app/Http/Kernel.php
  backend/app/Http/Middleware/CheckApiKey.php
  backend/app/Http/Middleware/CheckHmac.php
  backend/app/Http/Middleware/EncryptJsonResponse.php
  backend/app/Models/ApiKey.php
  backend/app/Models/Preference.php
  backend/app/Models/PreferenceDay.php
  backend/app/Providers/RouteServiceProvider.php
  backend/config/cors.php
  backend/database/migrations/2024_09_09_005134_create_preferences_table.php
  backend/database/migrations/2024_12_09_213129_create_api_keys_table.php
  backend/database/migrations/2024_12_12_140422_create_preference_days_table.php
  backend/database/seeders/DatabaseSeeder.php
  backend/database/sql/template/pupt_flss_official_v1.sql
  backend/routes/api.php
  frontend/src/app/core/animations/animations.ts
  frontend/src/app/core/components/admin/faculty-pref/faculty-pref.component.ts
  frontend/src/app/core/components/admin/scheduling/scheduling.component.html
  frontend/src/app/core/components/admin/scheduling/scheduling.component.ts
  frontend/src/app/core/components/faculty/home/home.component.scss
  frontend/src/app/core/components/faculty/preferences/preferences.component.html
  frontend/src/app/core/components/faculty/preferences/preferences.component.scss
  frontend/src/app/core/components/faculty/preferences/preferences.component.ts
  frontend/src/app/core/components/superadmin/maintenance/curriculum/curriculum-detail/curriculum-detail.component.ts
  frontend/src/app/core/models/scheduling.model.ts
  frontend/src/app/core/services/faculty/preference/preferences.service.ts
  frontend/src/app/shared/dialog-action/dialog-action.component.html
  frontend/src/app/shared/dialog-action/dialog-action.component.ts
  frontend/src/app/shared/dialog-day-time/dialog-day-time.component.html
  frontend/src/app/shared/dialog-day-time/dialog-day-time.component.scss
  frontend/src/app/shared/dialog-day-time/dialog-day-time.component.ts
  frontend/src/app/shared/dialog-pref/dialog-pref.component.html
  frontend/src/app/shared/dialog-pref/dialog-pref.component.ts
  frontend/src/app/shared/dialog-scheduling/dialog-scheduling.component.html
  frontend/src/app/shared/dialog-scheduling/dialog-scheduling.component.scss
  frontend/src/app/shared/dialog-scheduling/dialog-scheduling.component.ts
  frontend/src/app/shared/table-header/table-header.component.ts
Labels: refactor
