Repository PUPT-FLSS-ORG/PUPT-FLSS, pull requests merged in 2025-01, with the labels that each got.

#94 XSS & SQL Injection Fuzzing with OWASP ZAP
  documents/IAS REPORT/XXS-SQL-INJECTION/FLS-BETA-2025-1-11-SQL-INJECT.csv
  documents/IAS REPORT/XXS-SQL-INJECTION/FLS-BETA-2025-1-11-XSS.csv
Labels: documentation, security

#101 Enhance generating PDF in Room and Curriculum Details Component
  frontend/src/app/core/components/superadmin/maintenance/curriculum/curriculum-detail/curriculum-detail.component.ts
  frontend/src/app/core/components/superadmin/maintenance/rooms/rooms.component.ts
Labels: enhancement

#102 Bug Fixes & Enhancements
  backend/app/Http/Controllers/AcademicYearController.php
  backend/app/Http/Controllers/CurriculumController.php
  backend/app/Http/Controllers/EmailController.php
  backend/app/Http/Controllers/PreferenceController.php
  backend/app/Http/Controllers/ReportsController.php
  backend/app/Http/Controllers/ScheduleController.php
  backend/app/Jobs/NotifyAdminOfPreferenceChangeJob.php
  backend/app/Jobs/ProcessExternalScheduleChange.php
  backend/database/schema/pupt_flss_db.sql
  backend/database/sql/data/pupt_flss_official_v1_mock_data.sql
  backend/database/sql/data/pupt_flss_official_v1_query.sql
  backend/database/sql/template/pupt_flss_partial.sql
  backend/routes/api.php
  frontend/src/app/core/components/admin/academic-year/academic-year.component.ts
  frontend/src/app/core/components/admin/manage-preferences/manage-preferences.component.html
  frontend/src/app/core/components/admin/manage-preferences/manage-preferences.component.scss
  frontend/src/app/core/components/admin/reports/report-faculty/report-faculty.component.html
  frontend/src/app/core/components/admin/reports/report-programs/report-programs.component.html
  frontend/src/app/core/components/admin/reports/report-rooms/report-rooms.component.html
  frontend/src/app/core/components/admin/reports/reports.component.scss
  frontend/src/app/core/components/superadmin/maintenance/curriculum/curriculum-detail/curriculum-detail.component.ts
  frontend/src/app/core/mocks/mock-curricula.json
  frontend/src/app/core/mocks/mock-subject.service.ts
  frontend/src/app/core/mocks/scheduling.jsonc
  frontend/src/app/core/services/admin/academic-year/academic-year.service.ts
  frontend/src/app/shared/dialog-scheduling/dialog-scheduling.component.html
  frontend/src/app/shared/dialog-scheduling/dialog-scheduling.component.ts
  frontend/src/app/shared/faculty-schedule-timetable/faculty-schedule-timetable.component.scss
Labels: fixed bug

#103 Add "Sunday" column for each table in PDF
  frontend/src/app/core/components/admin/reports/report-faculty/report-faculty.component.ts
  frontend/src/app/core/components/admin/reports/report-programs/report-programs.component.ts
  frontend/src/app/core/components/admin/reports/report-rooms/report-rooms.component.ts
Labels: fixed bug

#104 Revisions to Chapters 1–3, Addition of Chapters 4 & 5, and Implementation Certificate Template
  documents/Certificate of Implementation.pdf
  documents/PUPT–FLSS Chapter 1 to 5 - Copy (Revisions-January).pdf
Labels: documentation

#108 Schedule Publishing Refactor
  backend/app/Http/Controllers/AuthController.php
  backend/app/Http/Controllers/External/v1/ExternalController.php
  backend/app/Http/Controllers/FacultyNotificationController.php
  backend/app/Http/Controllers/PreferenceController.php
  backend/app/Http/Controllers/ReportsController.php
  backend/app/Http/Controllers/ScheduleController.php
  backend/app/Http/Kernel.php
  backend/app/Http/Middleware/CustomRateLimiter.php
  backend/app/Models/Faculty.php
  backend/app/Models/FacultySchedulePublication.php
  backend/app/Models/Schedule.php
  backend/app/Services/RateLimiterService.php
  backend/database/migrations/2025_01_22_remove_is_published_from_schedules_table.php
  backend/database/migrations/2025_01_25_182406_restructure_faculty_schedule_publication_table.php
  backend/database/schema/pupt_flss_db.sql
  backend/resources/views/emails/load_schedule_published.blade.php
  backend/routes/api.php
  backend/tests/Requests/http.txt
  frontend/angular.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/core/animations/animations.ts
  frontend/src/app/core/components/admin/academic-year/academic-year.component.html
  frontend/src/app/core/components/admin/main/main.component.html
  frontend/src/app/core/components/admin/manage-preferences/manage-preferences.component.html
  frontend/src/app/core/components/admin/reports/report-faculty/report-faculty.component.html
  frontend/src/app/core/components/admin/reports/report-faculty/report-faculty.component.ts
  frontend/src/app/core/components/admin/reports/report-programs/report-programs.component.html
  frontend/src/app/core/components/admin/reports/reports.component.scss
  frontend/src/app/core/components/admin/scheduling/scheduling.component.html
  frontend/src/app/core/components/admin/scheduling/scheduling.component.scss
  frontend/src/app/core/components/admin/scheduling/scheduling.component.ts
  frontend/src/app/core/components/faculty/home/home.component.html
  frontend/src/app/core/components/faculty/home/home.component.scss
  frontend/src/app/core/components/faculty/home/home.component.ts
  frontend/src/app/core/components/faculty/main/main.component.scss
  frontend/src/app/core/components/superadmin/main/main.component.html
  frontend/src/app/core/services/auth/auth.service.ts
  frontend/src/app/core/services/faculty/faculty-notification/faculty-notification.service.ts
  frontend/src/app/shared/dialog-admin-login/dialog-admin-login.component.ts
  frontend/src/app/shared/dialog-faculty-login/dialog-faculty-login.component.html
  frontend/src/app/shared/dialog-faculty-login/dialog-faculty-login.component.ts
  frontend/src/app/shared/dialog-redirect/dialog-redirect.component.html
  frontend/src/app/shared/dialog-view-schedule/dialog-view-schedule.component.html
  frontend/src/styles.scss
Labels: refactor
